### PR TITLE
Dup current attributes on saving

### PR DESCRIPTION
**Pull request by fatkodima**
See https://github.com/rails/rails/pull/53440 for the problem description.

### CODE REVIEW

**Comment by mperham** [comment]
I think it's reasonable to `dup` as we really want to serialize this data. I am concerned that if we are `push_bulk`ing 10,000 jobs, we'll create 10,000 copies of the Hash but I guess that's unavoidable. What if we serialize the jobs at the time of `push` failure and send the serialized copy when recovering?

**Comment by fatkodima** [comment]
The current approach looks the simplest to me. 

> What if we serialize the jobs at the time of push failure and send the serialized copy when recovering?

This needs to be implemented in the sidekiq-pro, right?

**Comment by mperham** [comment]
Yes, but I'm ok with that. This is a small but subtle improvement to reliability.

**Comment by fatkodima** [comment]
Given that the rails PR is about to be merged (https://github.com/rails/rails/pull/53440#issuecomment-2436384115) and this will now return a copy on each call, wdyt about making a conditional check on rails version and dup if needed?

**Comment by mperham** [comment]
I just gave you access since you've been a great collaborator but I want to be clear that I don't expect free labor from you. I'm happy to pay for PRs to Pro/Ent, I'm not sure how to do this but I'm open to it.

**Comment by mperham** [comment]
If they are going to dup, let's just leave things as is. I'd say upgrade Rails to get the new behavior.

**Comment by fatkodima** [comment]
Thanks, accepted. No worries, I don't need payments for the great OSS projects I use 😄.

I would still prefer to maybe have this PR given how simple it is, because rails PR will not be backported and will only be in the yet to be released rails version. Most people are not on the latest versions and can have this issue unnoticed. We are currently on latest rails 7.2 and I don't know when we will be on 8.0, but this already caused an issue for us for the job to ran on the incorrect shard (shard was configured by `Current`). We can avoid the potential performance penalty by adding a check for rails version.

**Comment by mperham** [comment]
I guess I will have Sidekiq Pro users on Rails < 8 for many years to come so it's best to fix this now.

**Comment by fatkodima** [comment]
So should I reopen and finish this PR (preferred) or create a new in the sidekiq-pro?

**Comment by mperham** [comment]
I'm ok using this PR.

**Comment by fatkodima** [comment]
Updated. I was incorrect - it will be rails 8.1, which will be released in half a year from now or even more.

**Comment by mperham** [comment]
And in rethinking about this, we really do want to serialize this data via `dup` when the middleware is run, because the payload push can be delayed and CurrentAttributes mutated during that time. Pro's reliable push delays it occasionally but transactional push delays it *every time*.

This could be a long-time source of mysterious bugs for Sidekiq users. I see this as a pretty high priority fix for anyone using transactional_push.

**Comment by mperham** [comment]
Oh wait, I'm wrong. The middleware doesn't run until the transaction commits anyways so it's not an issue with transactional_push.

**Pull request merged**
