### PR TITLE
Fix bug in Deadset#kill ex param

### PR DESCRIPTION
**Pull request by rr3tt**
Was trying this out on the latest release and there was a typo: `opt` should have been `opts` 🤦 
Also corrected the yardoc to render the options correctly.

### CODE REVIEW

**Comment by mperham** [comment]
Can you add a test?

**Comment by mperham** [comment]
Thank you!

**Comment by fatkodima** [comment]
@mperham wdyt about configuring auto-squashing PRs when merging? This makes git history cleaner and easier to revert things.

**Comment by mperham** [comment]
I've never once cared about git history but if you want it on, go for it.

**Comment by fatkodima** [comment]
Thank you 👍. I can't do it - only the repository owner can change the setting.

**Comment by mperham** [comment]
I’m not sure how to do it. I disabled merge commits for PRs, not sure if that’s it.

**Comment by fatkodima** [comment]
Yeah, under the "Pull Requests" section in "Settings" should be only "Allow squash merging" checked.

**Pull request merged**
