### PR TITLE
chore: Update Redis version requirement to 5.2.0 or greater

### PR DESCRIPTION
**Pull request by badde-media**
Bugfix for issue #6335

### CODE REVIEW

**Review by badde-media — COMMENTED** [review]
https://github.com/sidekiq/sidekiq/issues/6335

**Comment by mperham** [comment]
Redis server, not the gem.

**Comment by badde-media** [comment]
Well it works after my fix.

**Comment by badde-media** [comment]
At least the app boots up. But log shhows a whole bunch of errors like this one:
```
worker           | 2024-06-19T19:34:42.656Z pid=231024 tid=4ezo ERROR: ERR Error running script (call to f_000a4c2f82df69db1780053377a2c9b0741570e0): @user_script:2: ERR value is not an integer or out of range (redis://localhost:6379)
```
Please correct me if I'm wrong, but doesn't
```
if ver < Gem::Version.new("6.2.0")
```
refer to the version of the Redis gem, which should be at least 6.2.0, but the most recent version of this gem being 5.2.0?

**Comment by mperham** [comment]
> refer to the version of the Redis gem, which should be at least 6.2.0, but the most recent version of this gem being 5.2.0?

Not at all. Sidekiq is telling you you are connected to Redis 6.0.16, so how could Redis version 6 not exist? We refer to the redis gem as redis-rb. Redis is the actual server and the latest version is 7.2.5.

https://github.com/redis/redis/releases/tag/7.2.5

**Pull request closed without merging**
