### PR TITLE
feat: Notify strict args violation with Proc

### PR DESCRIPTION
**Pull request by ixti**
This way one can "track" all the "bad" places in production via bug tracking systems (like Sentry), or write those to logger.

### CODE REVIEW

**Comment by fatkodima** [comment]
Imo, strict args violations should be caught in development. Having those in production is an error. Don't think we need to have a special handling except the raising, as now. There is no point in silently logging it, or having a callback that reports it somewhere. 
Exception trace services should already report unhandled exceptions from sidekiq to their services (at least the ones I used before, bugsnag for example, already does this).

**Comment by ixti** [comment]
@fatkodima I agree with that. But if you test suite is not 95% coverage and like 60% you end up with:

---

testing in production

---

Although, after opening the PR I just realized that probably it's not a good proposal indeed, LOL

**Comment by fatkodima** [comment]
Even without good coverage, that error will be reported by the error reporting service automatically and just logging is probably 100% useless.

**Comment by ixti** [comment]
> Even without good coverage, that error will be reported by the error reporting service automatically and just logging is probably 100% useless.

That's true. But if deployment takes 20 mins, cathing a failure in production that is facing 100% customers is not the most fun experience. :D

**Pull request closed without merging**
